from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent

NABAT_PAPER_DIR = PROJECT_DIR / "data" / "nabat_paper_31"
NABAT_PAPER_TRAINVAL_DIR = NABAT_PAPER_DIR / "trainval"
NABAT_PAPER_TEST_DIR = NABAT_PAPER_DIR / "test"
NABAT_PAPER_WAV_DIR = PROJECT_DIR / "data"
NABAT_PAPER_SPEC_CACHE = NABAT_PAPER_TRAINVAL_DIR / "spec_cache"
NABAT_PAPER_TEST_SPEC_CACHE = NABAT_PAPER_TEST_DIR / "spec_cache"

FT_DATA_DIR = NABAT_PAPER_TRAINVAL_DIR
FT_METADATA_PATH = NABAT_PAPER_TRAINVAL_DIR / "pulses_train.csv"
SSL_DATA_DIR = NABAT_PAPER_TRAINVAL_DIR
SSL_METADATA_PATH = FT_METADATA_PATH

# output
CHECKPOINT_DIR = PROJECT_DIR / "checkpoints"
BEST_CKPT = CHECKPOINT_DIR / "vit_lfpe_ssl_best.pt"
FT_BEST_CKPT = CHECKPOINT_DIR / "vit_lfpe_bat_finetune_best.pt"

# experiment
RANDOM_SEED = 42
VAL_TEST_SIZE = 0.15
BATCH_SIZE = 16
NUM_WORKERS = 0
USE_SPEC_CACHE = True
USE_NABAT_PREPROCESSING = True
SPEC_CACHE_VERSION = "nabat_v2_f16_100"
SPEC_CACHE_DTYPE = "float16"
SUPERVISED_SPEC_AUG = True

# SSL pretrain
MASK_RATIO = 0.75
SEM_UTTERANCE_WEIGHT = 1.0

SEM_CONTRASTIVE_WEIGHT = 0.25
CONTRASTIVE_EVERY = 4
CONTRASTIVE_VIEW_FRAC = 0.65  # left/right crop (not used)
SEM_SEP_WEIGHT = 0.5
SEP_EVERY = 4
SEP_GAIN_RATIO_MIN = 0.7
SEP_GAIN_RATIO_MAX = 1.4

SEM_JIGSAW_WEIGHT = 0.5
JIGSAW_EVERY = 4
JIGSAW_EVERY_OFFSET = 2
JIGSAW_PARTS = 5
CONTRASTIVE_EVERY_OFFSET = 0
SEP_EVERY_OFFSET = 1


BASE_LR = 1e-4
MAX_EPOCHS = 40
PATIENCE = 8
WARMUP_EPOCHS = 5

# finetune 
LOAD_SSL_PRETRAIN = True
FT_MAX_EPOCHS = 40
FT_PATIENCE = 5
FT_ENCODER_LR_SSL = 2e-5
FT_ENCODER_LR_NO_SSL = 1e-4
FT_HEAD_LR = 1e-4
FT_WEIGHT_DECAY = 0.05
FT_LABEL_SMOOTHING = 0.1
FT_MIXUP_ALPHA = 0.2
FT_DROPOUT = 0.3
FT_PLATEAU_PATIENCE = 3
